import type { ExchangeRecord } from '../../core/index.ts'

export function exchange(over: Partial<ExchangeRecord> = {}): ExchangeRecord {
  return {
    index: 0,
    playerFaces: [4, 3],
    playerFacesBeforeReroll: null,
    rerolled: false,
    enemyFaces: [2, 1],
    playerTotal: 7,
    enemyTotal: 3,
    playerBonusApplied: 0,
    enemyBonusApplied: 0,
    winner: 'player',
    tieBreak: false,
    playerCrit: false,
    enemyCrit: false,
    playerCritFactor: 1,
    enemyCritFactor: 1,
    playerCritSource: null,
    damageDealt: 4,
    damageTaken: 0,
    blocked: 0,
    blockedBy: null,
    thickSkinReduced: 0,
    ironGuardReduced: 0,
    sharpBladeBonus: 0,
    bloodlustBonus: 0,
    weightedDiceClamps: 0,
    cursedClamps: 0,
    thornDamage: 0,
    riposteDamage: 0,
    healed: 0,
    enemyHealed: 0,
    playerHpAfter: 10,
    enemyHpAfter: 5,
    multiplierGained: 0.1,
    multiplierGainedMilli: 100,
    multiplierAfterMilli: 100,
    upgradeTriggers: [],
    ...over,
  }
}
