export const TICKS_PER_SECOND = 60

export const MILLI = 1000

export const CONFIG = {
  minBuyIn: 100,
  defaultBuyIn: 100,
  buyInPresets: [100, 250, 500, 1000] as readonly number[],

  fightsPerStage: 5,

  minBetPercent: 4,
  maxBetPercent: 100,
  bossMaxBetPercent: 100,
  betPresetPercents: { low: 10, medium: 25, high: 50 },

  targetGrowthPercent: 7,
  targetGrowthPerStagePercent: 0,
  targetFloorFirstPermilleOfBuyIn: 0,
  targetFloorGrowthPercent: 115,

  skipPawnPermilleOfBuyIn: 10,

  failedCheckpointFeePercent: 10,

  playerBaseHp: 10,
  playerBaseDice: [6, 6] as readonly number[],
  playerBaseBonus: 0,

  fullKoMultiplierMilli: 1400,
  koBonusMilli: 200,
  bossFullKoMultiplierMilli: 2000,
  bossKoBonusMilli: 500,
  walkAwayKeepMilli: 500,
  critFactor: 2,

  enemyDice: [6, 6] as readonly number[],
  enemyBaseHp: 8,
  enemyHpPerFightMilli: 150,
  enemyHpSpread: 2,
  enemyBaseBonusMilli: -540,
  enemyBonusPerFightMilli: 303,
  enemyBonusCurveMicro: 3950,
  enemyBonusRampFights: 23,
  enemyBonusLatePerFightMilli: 0,
  enemyMinHp: 3,
  bossExtraHp: 4,
  bossBonusMilli: 100,
  bossBonusPerStageMilli: -50,

  enemyNames: [
    'Goblin',
    'Rat King',
    'Bandit',
    'Skeleton',
    'Slime',
    'Orc',
    'Cultist',
    'Wolf',
    'Troll',
    'Ghoul',
  ] as readonly string[],
  bossNames: [
    'Goblin Warlord',
    'Bone Tyrant',
    'The Hollow King',
    'Mire Hydra',
    'Iron Golem',
    'Witch of Ash',
    'Dread Knight',
    'Ogre Chieftain',
  ] as readonly string[],
  enemyTraitWeights: {
    plain: 4,
    tough: 2,
    brute: 2,
    armored: 1,
    savage: 1,
    vicious: 1,
    lucky: 1,
  },
  bossTraitWeights: {
    enrage: 1,
    regenerate: 1,
    ironhide: 1,
    executioner: 1,
  },
  traitToughHpPercent: 130,
  traitBruteBonus: 1,
  traitArmorReduction: 1,
  traitSavageCritFactor: 3,
  traitViciousDamage: 1,
  traitLuckyTieDamage: 1,
  bossEnrageBonus: 1,
  bossRegenerateHp: 1,
  bossIronhideReduction: 2,
  bossExecutionerDamage: 2,

  upgradeEffects: {
    weightedDiceMinFaceStep: 1,
    sharpBladeDamage: 1,
    secondWindRerolls: 1,
    vitalityHp: 3,
    shieldBlockAmount: 4,
    loadedDiceCritTotal: 10,
    insuranceRefundMilli: 200,
    finisherKoBonusMilli: 300,
    intimidateEnemyHpPercent: 20,
    vampireHeal: 3,
    thickSkinReduction: 1,
  },
  upgradeMaxCopies: {
    weightedDice: 1,
    sharpBlade: 3,
    secondWind: 2,
    vitality: 2,
    shield: 2,
    loadedDice: 1,
    escapeRope: 1,
    insurance: 2,
    finisher: 3,
    intimidate: 2,
    vampire: 1,
    thickSkin: 2,
  },

  shopOfferCount: 3,
}
