export { TICKS_PER_SECOND, CONFIG, MILLI, RULES_VERSION } from './config.ts'
export type { LevelDef } from './config.ts'
export {
  createGame,
  createGameFromLog,
  replay,
  clampBet,
  minBetFor,
  failedCheckpointFee,
  maxBetFor,
  isValidBuyIn,
  targetForStage,
  targetGrowthPercentForStage,
  shopOrderForFight,
  shopOffersForFight,
} from './game.ts'
export { levelDef, levelInfo, koMultiplierMilliForLevel, enemyBonusMilliFor } from './levels.ts'
export {
  UPGRADES,
  UPGRADE_IDS,
  upgradeDef,
  getUpgrade,
  computeMods,
  countOwned,
  isUseful,
} from './upgrades.ts'
export type { FightMods } from './upgrades.ts'
export {
  generateEnemy,
  stageOfFight,
  levelOfFight,
  isBossFight,
  archetypeOf,
  diceText,
  traitText,
  enemyBonusMilliForFight,
  normalTraitWeights,
  NORMAL_TRAITS,
  BOSS_TRAITS,
} from './enemies.ts'
export type { EnemyDef } from './enemies.ts'
export {
  createSimFight,
  rollExchange,
  hasDoubles,
  payoutAt,
  walkAwayPayoutAt,
  walkAwayPartsAt,
  lossPayoutAt,
  enemyMaxHpWithMods,
  damageMultiplierMilli,
  fullKoMultiplierMilliFor,
  koBonusMilliFor,
  enemyCurrentBonus,
  playerCurrentBonus,
  playerMaxFace,
  currentWalkAwayPayout,
  currentWalkAwayParts,
  canWalkAway,
  fightPayout,
  resultTriggers,
} from './fight.ts'
export type { SimFight, WalkAwayParts } from './fight.ts'
export { mulberry32, createStream, deriveSeed, hashString } from './rng.ts'
export type { Rng } from './rng.ts'
export type {
  Phase,
  Action,
  LogEntry,
  Game,
  GameState,
  FightState,
  FightStatus,
  FightResult,
  FightOutcome,
  EnemyState,
  EnemyTraitId,
  NormalTraitId,
  BossTraitId,
  Archetype,
  PlayerFightState,
  ExchangeRecord,
  ExchangeWinner,
  CritSource,
  CheckpointResult,
  CheckpointOutcome,
  GameOverReason,
  BetPreset,
  BetPresetId,
  LevelInfo,
  Upgrade,
  UpgradeDef,
  UpgradeId,
  UpgradeTrigger,
  ShopOffer,
} from './types.ts'
